# API settings
api:
  api_title: "3D Generation Pipeline Service"
  host: "0.0.0.0"
  port: 10006

# Output settings
output:
  save_generated_files: false
  send_generated_files: false
  compression: false
  output_dir: "generated_outputs"


# Trellis model settings
trellis:
  model_id: "jetx/trellis-image-large"
  sparse_structure_steps: 8
  sparse_structure_cfg_strength: 5.75
  slat_steps: 19
  slat_cfg_strength: 2.5
  num_oversamples: 3
  gpu: 0

# Qwen model settings
qwen:
  base_model_path: "Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-8steps-V1.0-bf16.safetensors"
  model_path: "Qwen/Qwen-Image-Edit-2509"
  height: 1024
  width: 1024
  num_inference_steps: 8
  true_cfg_scale: 1.0
  prompt_path: "config/qwen_edit_prompt.json"
  gpu: 0
  dtype: "bf16"
  

# Background removal model settings
background_removal:
  model_id: "michealthegandalf11/alpha-extract"
  input_image_size: [1024, 1024]
  output_image_size: [518, 518]
  padding_percentage: 0.2
  limit_padding: true
  gpu: 0